/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package masamuscular;
import java.text.DecimalFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author 33
 */
public class FrmCalculoMasa extends javax.swing.JFrame {

    double peso, altura, imc;
            
    public FrmCalculoMasa() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setIconImage(new ImageIcon(getClass().getResource("/img/FrmCalculoMasa_icono.png")).getImage());

        
        lblSobrePeso.setVisible(false);
        lblObesidad.setVisible(false);
        lblNormal.setVisible(false);
        lblBajoPeso.setVisible(false);
        lblObesidadExtrema.setVisible(false);
        lbl_IMC.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtPeso = new javax.swing.JTextField();
        txtAltura = new javax.swing.JTextField();
        lblPeso = new javax.swing.JLabel();
        lblAltura = new javax.swing.JLabel();
        lbl_IMC = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        lblObesidadExtrema = new javax.swing.JLabel();
        lblBajoPeso = new javax.swing.JLabel();
        lblNormal = new javax.swing.JLabel();
        lblObesidad = new javax.swing.JLabel();
        lblSobrePeso = new javax.swing.JLabel();
        lblRuleta = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuCalcular = new javax.swing.JMenu();
        mnuCalcularIMC = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenuItem();
        mnuInfo = new javax.swing.JMenu();
        mnuInfoApp = new javax.swing.JMenuItem();
        mnuInfoDesar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(".: Cálculo de Indice de Masa Muscular :.");

        jPanel1.setBackground(new java.awt.Color(36, 36, 47));
        jPanel1.setLayout(null);

        txtPeso.setBackground(new java.awt.Color(36, 36, 47));
        txtPeso.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        txtPeso.setForeground(new java.awt.Color(255, 255, 255));
        txtPeso.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPeso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(168, 238, 214)));
        txtPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesoActionPerformed(evt);
            }
        });
        txtPeso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPesoKeyTyped(evt);
            }
        });
        jPanel1.add(txtPeso);
        txtPeso.setBounds(210, 100, 140, 44);

        txtAltura.setBackground(new java.awt.Color(36, 36, 47));
        txtAltura.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        txtAltura.setForeground(new java.awt.Color(255, 255, 255));
        txtAltura.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAltura.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(168, 238, 214)));
        txtAltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlturaActionPerformed(evt);
            }
        });
        txtAltura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAlturaKeyTyped(evt);
            }
        });
        jPanel1.add(txtAltura);
        txtAltura.setBounds(210, 170, 140, 44);

        lblPeso.setFont(new java.awt.Font("Montserrat Black", 0, 24)); // NOI18N
        lblPeso.setForeground(new java.awt.Color(255, 255, 255));
        lblPeso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPeso.setText("Peso (Kg)");
        jPanel1.add(lblPeso);
        lblPeso.setBounds(50, 110, 140, 30);

        lblAltura.setFont(new java.awt.Font("Montserrat Black", 0, 24)); // NOI18N
        lblAltura.setForeground(new java.awt.Color(255, 255, 255));
        lblAltura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAltura.setText("Altura (cm)");
        jPanel1.add(lblAltura);
        lblAltura.setBounds(40, 180, 160, 30);

        lbl_IMC.setFont(new java.awt.Font("Montserrat Light", 0, 36)); // NOI18N
        lbl_IMC.setForeground(new java.awt.Color(168, 238, 214));
        lbl_IMC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_IMC.setText("IMC:");
        jPanel1.add(lbl_IMC);
        lbl_IMC.setBounds(74, 230, 580, 59);

        lblTitulo.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 40)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("INDÍCE DE MASA CORPORAL");
        jPanel1.add(lblTitulo);
        lblTitulo.setBounds(0, 20, 720, 49);

        btnCalcular.setBackground(new java.awt.Color(60, 89, 88));
        btnCalcular.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        btnCalcular.setForeground(new java.awt.Color(165, 237, 212));
        btnCalcular.setText("C A L C U L A R");
        btnCalcular.setBorder(null);
        btnCalcular.setBorderPainted(false);
        btnCalcular.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        jPanel1.add(btnCalcular);
        btnCalcular.setBounds(480, 100, 198, 44);

        btnLimpiar.setBackground(new java.awt.Color(60, 89, 88));
        btnLimpiar.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(165, 237, 212));
        btnLimpiar.setText("L I M P I A R");
        btnLimpiar.setBorder(null);
        btnLimpiar.setBorderPainted(false);
        btnLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiar);
        btnLimpiar.setBounds(480, 170, 198, 44);

        btnSalir.setBackground(new java.awt.Color(54, 28, 28));
        btnSalir.setFont(new java.awt.Font("Montserrat Medium", 0, 24)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("S A L I R");
        btnSalir.setBorder(null);
        btnSalir.setBorderPainted(false);
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir);
        btnSalir.setBounds(400, 590, 260, 52);

        btnVolver.setBackground(new java.awt.Color(38, 38, 56));
        btnVolver.setFont(new java.awt.Font("Montserrat Medium", 0, 24)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("R E G R E S A R");
        btnVolver.setBorder(null);
        btnVolver.setBorderPainted(false);
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver);
        btnVolver.setBounds(50, 590, 260, 52);

        lblObesidadExtrema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/5.png"))); // NOI18N
        lblObesidadExtrema.setDisabledIcon(null);
        jPanel1.add(lblObesidadExtrema);
        lblObesidadExtrema.setBounds(340, 490, 140, 70);

        lblBajoPeso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/4.png"))); // NOI18N
        lblBajoPeso.setDisabledIcon(null);
        jPanel1.add(lblBajoPeso);
        lblBajoPeso.setBounds(250, 490, 140, 70);

        lblNormal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/3.png"))); // NOI18N
        lblNormal.setDisabledIcon(null);
        jPanel1.add(lblNormal);
        lblNormal.setBounds(260, 430, 140, 120);

        lblObesidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/49c4ff91-acf6-4e7a-9674-01810467386f-[Convertido]3.png"))); // NOI18N
        lblObesidad.setDisabledIcon(null);
        jPanel1.add(lblObesidad);
        lblObesidad.setBounds(310, 430, 140, 130);

        lblSobrePeso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/49c4ff91-acf6-4e7a-9674-01810467386f-[Convertido]2.png"))); // NOI18N
        lblSobrePeso.setDisabledIcon(null);
        jPanel1.add(lblSobrePeso);
        lblSobrePeso.setBounds(330, 410, 50, 150);

        lblRuleta.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        lblRuleta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/49c4ff91-acf6-4e7a-9674-01810467386f-[Convertido].png"))); // NOI18N
        jPanel1.add(lblRuleta);
        lblRuleta.setBounds(90, 200, 560, 450);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(30, 230, 660, 10);

        mnuCalcular.setText("Calcular");

        mnuCalcularIMC.setText("Calcular IMC");
        mnuCalcularIMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCalcularIMCActionPerformed(evt);
            }
        });
        mnuCalcular.add(mnuCalcularIMC);

        mnuSalir.setText("Salir");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        mnuCalcular.add(mnuSalir);

        jMenuBar1.add(mnuCalcular);

        mnuInfo.setText("Info");

        mnuInfoApp.setText("Sobre la Aplicación");
        mnuInfoApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuInfoAppActionPerformed(evt);
            }
        });
        mnuInfo.add(mnuInfoApp);

        mnuInfoDesar.setText("Sobre los Desarrolladores");
        mnuInfo.add(mnuInfoDesar);

        jMenuBar1.add(mnuInfo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlturaActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        if(txtPeso.getText().isEmpty() || txtAltura.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "No se puede dejar ningún campo vacío, inténtelo nuevamente.", "Campos Vacíos", JOptionPane.WARNING_MESSAGE);
        }

        else
        {
            peso = Double.parseDouble(txtPeso.getText());
            altura = (Double.parseDouble(txtAltura.getText()))/100;


            imc = peso/Math.pow(2, altura);

            DecimalFormat df = new DecimalFormat("0.0000");

            lbl_IMC.setVisible(true);
            lbl_IMC.setText("IMC " + String.valueOf(df.format(imc)));

            if(imc < 18.5)
            {
                lblBajoPeso.setVisible(true);
                lblNormal.setVisible(false);
                lblSobrePeso.setVisible(false);
                lblObesidad.setVisible(false);
                lblObesidadExtrema.setVisible(false);

            }

            if((imc >= 18.5) && (imc < 25))
            {
                lblBajoPeso.setVisible(false);
                lblNormal.setVisible(true);
                lblSobrePeso.setVisible(false);
                lblObesidad.setVisible(false);
                lblObesidadExtrema.setVisible(false);
            }

            if((imc >= 25) && (imc <= 30))
            {
                lblBajoPeso.setVisible(false);
                lblNormal.setVisible(false);
                lblSobrePeso.setVisible(true);
                lblObesidad.setVisible(false);
                lblObesidadExtrema.setVisible(false);
            }

            if((imc >= 30) && (imc < 35))
            {
                lblBajoPeso.setVisible(false);
                lblNormal.setVisible(false);
                lblSobrePeso.setVisible(false);
                lblObesidad.setVisible(true);
                lblObesidadExtrema.setVisible(false);
            }

            if(imc > 35)
            {
                lblBajoPeso.setVisible(false);
                lblNormal.setVisible(false);
                lblSobrePeso.setVisible(false);
                lblObesidad.setVisible(false);
                lblObesidadExtrema.setVisible(true);
            }
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        FrmPrincipal obj = new FrmPrincipal();
        obj.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuSalirActionPerformed

    private void mnuInfoAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuInfoAppActionPerformed
        FrmInfo obj = new FrmInfo();
        obj.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_mnuInfoAppActionPerformed

    private void mnuCalcularIMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCalcularIMCActionPerformed
        FrmCalculoMasa obj = new FrmCalculoMasa();
        obj.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_mnuCalcularIMCActionPerformed

    private void txtPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesoActionPerformed

    private void txtPesoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesoKeyTyped
        char tecla;
        
        tecla = evt.getKeyChar();
        
        if (tecla < '0' || tecla > '9') evt.consume();
    }//GEN-LAST:event_txtPesoKeyTyped

    private void txtAlturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAlturaKeyTyped
        char tecla;
        
        tecla = evt.getKeyChar();
        
        if (tecla < '0' || tecla > '9') evt.consume();
    }//GEN-LAST:event_txtAlturaKeyTyped

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtAltura.setText("");
        txtPeso.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCalculoMasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCalculoMasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCalculoMasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCalculoMasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCalculoMasa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVolver;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAltura;
    private javax.swing.JLabel lblBajoPeso;
    private javax.swing.JLabel lblNormal;
    private javax.swing.JLabel lblObesidad;
    private javax.swing.JLabel lblObesidadExtrema;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JLabel lblRuleta;
    private javax.swing.JLabel lblSobrePeso;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lbl_IMC;
    private javax.swing.JMenu mnuCalcular;
    private javax.swing.JMenuItem mnuCalcularIMC;
    private javax.swing.JMenu mnuInfo;
    private javax.swing.JMenuItem mnuInfoApp;
    private javax.swing.JMenuItem mnuInfoDesar;
    private javax.swing.JMenuItem mnuSalir;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JTextField txtPeso;
    // End of variables declaration//GEN-END:variables
}
