/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package masamuscular;

import javax.swing.ImageIcon;

/**
 *
 * @author 33
 */
public class FrmDesar extends javax.swing.JFrame {

    /**
     * Creates new form FrmDesar
     */
    public FrmDesar() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setIconImage(new ImageIcon(getClass().getResource("/img/FrmDesar_icono.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblCarlosIG = new javax.swing.JLabel();
        lblCarlos = new javax.swing.JLabel();
        lblCarlosFoto1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblKevin = new javax.swing.JLabel();
        lblKevinIG = new javax.swing.JLabel();
        lblCarlosFoto = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lblCarrera = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuCalcular = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenuItem();
        mnuInfo = new javax.swing.JMenu();
        mnuInfoApp = new javax.swing.JMenuItem();
        mnuInfoDesar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(".: Información sobre el Desarrollador :.");

        jPanel1.setBackground(new java.awt.Color(36, 36, 47));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(51, 51, 62));

        lblCarlosIG.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 36)); // NOI18N
        lblCarlosIG.setForeground(new java.awt.Color(255, 255, 255));
        lblCarlosIG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCarlosIG.setText("@whos.lunnna");

        lblCarlos.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        lblCarlos.setForeground(new java.awt.Color(255, 255, 255));
        lblCarlos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCarlos.setText("Carlos Luna");

        lblCarlosFoto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCarlosFoto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/49c4ff91-acf6-4e7a-9674-01810467386f-[Convertido] (1) (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCarlosIG, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
            .addComponent(lblCarlos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblCarlosFoto1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(339, Short.MAX_VALUE)
                .addComponent(lblCarlos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCarlosIG, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(28, 28, 28)
                    .addComponent(lblCarlosFoto1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, Short.MAX_VALUE)
                    .addGap(129, 129, 129)))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 20, 330, 460);

        jPanel4.setBackground(new java.awt.Color(51, 51, 62));

        lblKevin.setFont(new java.awt.Font("Montserrat SemiBold", 0, 33)); // NOI18N
        lblKevin.setForeground(new java.awt.Color(255, 255, 255));
        lblKevin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKevin.setText("Kevin Montilla");

        lblKevinIG.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 36)); // NOI18N
        lblKevinIG.setForeground(new java.awt.Color(255, 255, 255));
        lblKevinIG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKevinIG.setText("@kev_nmontilla");

        lblCarlosFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCarlosFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/descarga.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblKevinIG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblKevin, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lblCarlosFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblCarlosFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 303, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblKevin, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblKevinIG, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(370, 20, 330, 460);

        lblFecha.setFont(new java.awt.Font("Montserrat SemiBold", 0, 24)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(255, 255, 255));
        lblFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFecha.setText("Junio del 2024");
        jPanel1.add(lblFecha);
        lblFecha.setBounds(0, 540, 720, 30);

        btnVolver.setBackground(new java.awt.Color(38, 38, 56));
        btnVolver.setFont(new java.awt.Font("Montserrat Medium", 0, 24)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("R E G R E S A R");
        btnVolver.setBorder(null);
        btnVolver.setBorderPainted(false);
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver);
        btnVolver.setBounds(50, 590, 260, 52);

        btnSalir.setBackground(new java.awt.Color(54, 28, 28));
        btnSalir.setFont(new java.awt.Font("Montserrat Medium", 0, 24)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("S A L I R");
        btnSalir.setBorder(null);
        btnSalir.setBorderPainted(false);
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir);
        btnSalir.setBounds(400, 590, 260, 52);

        lblCarrera.setFont(new java.awt.Font("Montserrat Light", 0, 36)); // NOI18N
        lblCarrera.setForeground(new java.awt.Color(255, 255, 255));
        lblCarrera.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCarrera.setText("Ingeniería en Información");
        jPanel1.add(lblCarrera);
        lblCarrera.setBounds(120, 490, 490, 40);

        jMenu1.setText("Calcular");

        mnuCalcular.setText("Calcular IMC");
        mnuCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCalcularActionPerformed(evt);
            }
        });
        jMenu1.add(mnuCalcular);

        mnuSalir.setText("Salir");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        jMenu1.add(mnuSalir);

        jMenuBar1.add(jMenu1);

        mnuInfo.setText("Info");

        mnuInfoApp.setText("Sobre la Aplicación");
        mnuInfoApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuInfoAppActionPerformed(evt);
            }
        });
        mnuInfo.add(mnuInfoApp);

        mnuInfoDesar.setText("Sobre los Desarrolladores");
        mnuInfoDesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuInfoDesarActionPerformed(evt);
            }
        });
        mnuInfo.add(mnuInfoDesar);

        jMenuBar1.add(mnuInfo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 672, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCalcularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuCalcularActionPerformed

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuSalirActionPerformed

    private void mnuInfoAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuInfoAppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuInfoAppActionPerformed

    private void mnuInfoDesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuInfoDesarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuInfoDesarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDesar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDesar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDesar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDesar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDesar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVolver;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblCarlos;
    private javax.swing.JLabel lblCarlosFoto;
    private javax.swing.JLabel lblCarlosFoto1;
    private javax.swing.JLabel lblCarlosIG;
    private javax.swing.JLabel lblCarrera;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblKevin;
    private javax.swing.JLabel lblKevinIG;
    private javax.swing.JMenuItem mnuCalcular;
    private javax.swing.JMenu mnuInfo;
    private javax.swing.JMenuItem mnuInfoApp;
    private javax.swing.JMenuItem mnuInfoDesar;
    private javax.swing.JMenuItem mnuSalir;
    // End of variables declaration//GEN-END:variables
}
