/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package masamuscular;

import javax.swing.ImageIcon;

/**
 *
 * @author 33
 */
public class FrmInfo extends javax.swing.JFrame {

    /**
     * Creates new form FrmInfo
     */
    public FrmInfo() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setIconImage(new ImageIcon(getClass().getResource("/img/FrmInfo_icono.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblParrafo1 = new javax.swing.JLabel();
        lblParrafo2 = new javax.swing.JLabel();
        lblParrafo3 = new javax.swing.JLabel();
        lblParrafo4 = new javax.swing.JLabel();
        lblImagen = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuCalcular = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenuItem();
        mnuInfo = new javax.swing.JMenu();
        mnuInfoApp = new javax.swing.JMenuItem();
        mnuInfoDesar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(".: Información sobre la Aplicación :.");

        jPanel1.setBackground(new java.awt.Color(36, 36, 47));
        jPanel1.setLayout(null);

        lblParrafo1.setFont(new java.awt.Font("Montserrat Light", 0, 18)); // NOI18N
        lblParrafo1.setForeground(new java.awt.Color(255, 255, 255));
        lblParrafo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblParrafo1.setText("Con nuestra aplicación de IMC, podrás verificar el índice de tu");
        jPanel1.add(lblParrafo1);
        lblParrafo1.setBounds(0, 50, 720, 59);

        lblParrafo2.setFont(new java.awt.Font("Montserrat Light", 0, 18)); // NOI18N
        lblParrafo2.setForeground(new java.awt.Color(255, 255, 255));
        lblParrafo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblParrafo2.setText("masa corporal, tan solo indicándonos tu peso y altura sabrás tu");
        jPanel1.add(lblParrafo2);
        lblParrafo2.setBounds(0, 90, 720, 59);

        lblParrafo3.setFont(new java.awt.Font("Montserrat Light", 0, 18)); // NOI18N
        lblParrafo3.setForeground(new java.awt.Color(255, 255, 255));
        lblParrafo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblParrafo3.setText("IMC, el cual es un indicador confiable de la obesidad y se usa para");
        jPanel1.add(lblParrafo3);
        lblParrafo3.setBounds(0, 130, 720, 59);

        lblParrafo4.setFont(new java.awt.Font("Montserrat Light", 0, 18)); // NOI18N
        lblParrafo4.setForeground(new java.awt.Color(255, 255, 255));
        lblParrafo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblParrafo4.setText("identificar las categorías de peso que pueden llevar a problemas de salud.");
        jPanel1.add(lblParrafo4);
        lblParrafo4.setBounds(0, 170, 720, 59);

        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/49c4ff91-acf6-4e7a-9674-01810467386f-[Convertido] (1).png"))); // NOI18N
        jPanel1.add(lblImagen);
        lblImagen.setBounds(90, 280, 530, 232);

        btnVolver.setBackground(new java.awt.Color(38, 38, 56));
        btnVolver.setFont(new java.awt.Font("Montserrat Medium", 0, 24)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("R E G R E S A R");
        btnVolver.setBorder(null);
        btnVolver.setBorderPainted(false);
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver);
        btnVolver.setBounds(50, 590, 260, 52);

        btnSalir.setBackground(new java.awt.Color(54, 28, 28));
        btnSalir.setFont(new java.awt.Font("Montserrat Medium", 0, 24)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("S A L I R");
        btnSalir.setBorder(null);
        btnSalir.setBorderPainted(false);
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir);
        btnSalir.setBounds(400, 590, 260, 52);

        jMenu1.setText("Calcular");

        mnuCalcular.setText("Calcular IMC");
        mnuCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCalcularActionPerformed(evt);
            }
        });
        jMenu1.add(mnuCalcular);

        mnuSalir.setText("Salir");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        jMenu1.add(mnuSalir);

        jMenuBar1.add(jMenu1);

        mnuInfo.setText("Info");

        mnuInfoApp.setText("Sobre la Aplicación");
        mnuInfoApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuInfoAppActionPerformed(evt);
            }
        });
        mnuInfo.add(mnuInfoApp);

        mnuInfoDesar.setText("Sobre los Desarrolladores");
        mnuInfoDesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuInfoDesarActionPerformed(evt);
            }
        });
        mnuInfo.add(mnuInfoDesar);

        jMenuBar1.add(mnuInfo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 672, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void mnuCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCalcularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuCalcularActionPerformed

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuSalirActionPerformed

    private void mnuInfoAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuInfoAppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuInfoAppActionPerformed

    private void mnuInfoDesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuInfoDesarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuInfoDesarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVolver;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblParrafo1;
    private javax.swing.JLabel lblParrafo2;
    private javax.swing.JLabel lblParrafo3;
    private javax.swing.JLabel lblParrafo4;
    private javax.swing.JMenuItem mnuCalcular;
    private javax.swing.JMenu mnuInfo;
    private javax.swing.JMenuItem mnuInfoApp;
    private javax.swing.JMenuItem mnuInfoDesar;
    private javax.swing.JMenuItem mnuSalir;
    // End of variables declaration//GEN-END:variables
}
