/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package masamuscular;

import javax.swing.ImageIcon;

/**
 *
 * @author 33
 */
public class FrmPrincipal extends javax.swing.JFrame {



    public FrmPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setIconImage(new ImageIcon(getClass().getResource("/img/FrmPrincipal_icono.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCalcular = new javax.swing.JButton();
        btnInfo = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnInfoDesar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuCalcular = new javax.swing.JMenu();
        mnuCalcularIMC = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenuItem();
        mnuInfo = new javax.swing.JMenu();
        mnuInfoApp = new javax.swing.JMenuItem();
        mnuInfoDesar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(".: Principal :.");

        jPanel1.setBackground(new java.awt.Color(36, 36, 47));

        btnCalcular.setBackground(new java.awt.Color(38, 38, 56));
        btnCalcular.setFont(new java.awt.Font("Montserrat Medium", 0, 24)); // NOI18N
        btnCalcular.setForeground(new java.awt.Color(168, 238, 214));
        btnCalcular.setText("C A L C U L A R");
        btnCalcular.setBorderPainted(false);
        btnCalcular.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        btnInfo.setBackground(new java.awt.Color(38, 38, 56));
        btnInfo.setFont(new java.awt.Font("Montserrat Medium", 0, 24)); // NOI18N
        btnInfo.setForeground(new java.awt.Color(168, 238, 214));
        btnInfo.setText("I N F O R M A C I Ó N  A P P");
        btnInfo.setBorderPainted(false);
        btnInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(54, 28, 28));
        btnSalir.setFont(new java.awt.Font("Montserrat Medium", 0, 24)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("S A L I R");
        btnSalir.setBorder(null);
        btnSalir.setBorderPainted(false);
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnInfoDesar.setBackground(new java.awt.Color(38, 38, 56));
        btnInfoDesar.setFont(new java.awt.Font("Montserrat Medium", 0, 24)); // NOI18N
        btnInfoDesar.setForeground(new java.awt.Color(168, 238, 214));
        btnInfoDesar.setText("S O B R E  N O S O T R O S");
        btnInfoDesar.setBorderPainted(false);
        btnInfoDesar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInfoDesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoDesarActionPerformed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Montserrat Black", 0, 65)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("IMC");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInfoDesar, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitulo))
                .addContainerGap(120, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCalcular, btnInfo, btnInfoDesar, btnSalir});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblTitulo)
                .addGap(30, 30, 30)
                .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnInfo)
                .addGap(18, 18, 18)
                .addComponent(btnInfoDesar)
                .addGap(18, 18, 18)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCalcular, btnInfo, btnInfoDesar, btnSalir});

        mnuCalcular.setText("Calcular");

        mnuCalcularIMC.setText("Calcular IMC");
        mnuCalcularIMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCalcularIMCActionPerformed(evt);
            }
        });
        mnuCalcular.add(mnuCalcularIMC);

        mnuSalir.setText("Salir");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        mnuCalcular.add(mnuSalir);

        jMenuBar1.add(mnuCalcular);

        mnuInfo.setText("Info");

        mnuInfoApp.setText("Sobre la Aplicación");
        mnuInfoApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuInfoAppActionPerformed(evt);
            }
        });
        mnuInfo.add(mnuInfoApp);

        mnuInfoDesar.setText("Sobre los Desarrolladores");
        mnuInfo.add(mnuInfoDesar);

        jMenuBar1.add(mnuInfo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        FrmCalculoMasa obj = new FrmCalculoMasa();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed
        FrmInfo obj = new FrmInfo();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnInfoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuSalirActionPerformed

    private void btnInfoDesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoDesarActionPerformed
        FrmDesar obj = new FrmDesar();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnInfoDesarActionPerformed

    private void mnuInfoAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuInfoAppActionPerformed
        FrmInfo obj = new FrmInfo();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnuInfoAppActionPerformed

    private void mnuCalcularIMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCalcularIMCActionPerformed
        FrmCalculoMasa obj = new FrmCalculoMasa();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnuCalcularIMCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnInfo;
    private javax.swing.JButton btnInfoDesar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JMenu mnuCalcular;
    private javax.swing.JMenuItem mnuCalcularIMC;
    private javax.swing.JMenu mnuInfo;
    private javax.swing.JMenuItem mnuInfoApp;
    private javax.swing.JMenuItem mnuInfoDesar;
    private javax.swing.JMenuItem mnuSalir;
    // End of variables declaration//GEN-END:variables
}
